[package]
name = "tokio-uds"
version = "0.1.2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-uds"
homepage = "https://github.com/tokio-rs/tokio-uds"
documentation = "https://docs.rs/tokio-uds"
description = """
Unix Domain sockets for Tokio
"""
categories = ["asynchronous"]

[badges]
travis-ci = { repository = "tokio-rs/tokio-uds" }
appveyor = { repository = "alexcrichton/tokio-uds" }

[dependencies]
bytes = "0.4"
mio = "0.6"
mio-uds = "0.6.1"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
log = "0.3"

[dev-dependencies]
env_logger = { version = "0.4", default-features = false }